### ISSUE TITLE
Script failed due to Action Plan feature missing

### ISSUE THREAD

**Issue by mailalokagrawal** [bgaldino/sm-quickstart#3]
The script kept failing for me as the scratch org did not have action plans enabled. I worked around this problem by adding "IndustriesActionPlan" to the feature list in the scratch org definition file.

**Comment by bgaldino** [comment]
Thanks - I checked in a quick fix to check for internal SFDC demo tools and include the Action Plan views and routes if detected - otherwise they are excluded.  This will be refactored to either extract and modify the sample community created by the Quickstart process and deploy (preferred),  or to check for specific org features and include required views and routes.
